Stwórz DataFrame zawierający informacje o 10 produktach w sklepie: nazwa, cena, ilość na
stanie, kategoria.
Wymagania:
Oczekiwany rezultat:
(proste)
Użyj słownika do utworzenia DataFrame
Wyświetl pierwsze 5 wierszy
Oblicz całkowitą wartość towaru (cena × ilość) i dodaj jako nową kolumnę
DataFrame z 10 produktami i kolumną 'WartośćCałkowita'

In [2]:
import pandas as pd

In [4]:
data = {
'Produkt': ['Laptop', 'Mysz', 'Klawiatura', 'Monitor', 'Słuchawki'],
'Cena': [3500, 80, 250, 1200, 350],
'Ilość na stanie': [45, 320, 150, 78, 210],
'Kategoria': [3.5, 4.2, 4.7, 4.4, 4.3]
}

df = pd.DataFrame(data)
df

      Produkt  Cena  Ilość na stanie  Kategoria
0      Laptop  3500               45        3.5
1        Mysz    80              320        4.2
2  Klawiatura   250              150        4.7
3     Monitor  1200               78        4.4
4   Słuchawki   350              210        4.3

In [5]:
df.head()

      Produkt  Cena  Ilość na stanie  Kategoria
0      Laptop  3500               45        3.5
1        Mysz    80              320        4.2
2  Klawiatura   250              150        4.7
3     Monitor  1200               78        4.4
4   Słuchawki   350              210        4.3

In [6]:
df["Wartość całkowita"] = df["Cena"] * df["Ilość na stanie"]

In [7]:
df

      Produkt  Cena  Ilość na stanie  Kategoria  Wartość całkowita
0      Laptop  3500               45        3.5             157500
1        Mysz    80              320        4.2              25600
2  Klawiatura   250              150        4.7              37500
3     Monitor  1200               78        4.4              93600
4   Słuchawki   350              210        4.3              73500